### DISCUSSION TITLE
Last value persistent during inverter switchoff

### DISCUSSION THREAD

**Discussion by Claudio1L** [alexdelprete/ha-abb-powerone-pvi-sunspec#120] [Ideas]
Ciao Alessandro

some release ago, sensors values were persistent (if not rebooted) during the night. Now they goes in an unknown state. Is it complex to include a setting to choose between persistent and not persistent? I'm still running the ABB integration in a separate instance to avoid upgrading and losing the persistence :-)

**Comment by alexdelprete** [comment]
when an integration is unavailable, its sensors go in unavailable state, this is how HA works and integrations should work. "unavailable" is a state. :)

Sorry, can't do much to help. I don't understand what you're trying to achieve, if you can explain better I can try to help.

**Reply by Claudio1L** [reply]
I built a bunch of counters that take in account the integration values as source. As you can see from the attached dashboard, if the source sensors are not persistent, everything breaks. I solved using one of the latest release that were persistent (2.6.6) running in a separate container and then exporting sensors to the main instance I'm able to maintain counters. 

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/97904190/3fbba106-ec01-432a-b567-34264371d868)

**Reply by alexdelprete** [reply]
Then you need to build a lot of trigger-based template sensors, that are persistent, like this:

```yaml
template:
  - trigger:
      - platform: state
        entity_id: sensor.abb_vsn300_ac_power
        not_to:
          - unavailable
          - unknown
    sensor:
      - name: ABB Inverter Power Stable
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        icon: mdi:solar-power
        state: "{{ trigger.to_state.state }}"
```

The "shadow" `sensor sensor.abb_vsn300_ac_power_stable` will be created, and when the real sensor `sensor sensor.abb_vsn300_ac_power` has a value, it uses its value, when the state is `unknown` or `unavailable`, it uses last known state.

When the real sensor is available, the state is the same:

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/ba76b022-9afb-4e5c-80da-bc36543b285b)


When the real sensor goes unavailable, you see last known state:

![image](https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/assets/7027842/714210da-3362-4320-b1b2-3c7a2e2337e3)

**Reply by alexdelprete** [reply]
If you don't want to use trigger-based template sensor, but a standard template sensor, here is another example:

```yaml
template:
  - sensor:
      - name: ABB Inverter Power Stable
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        icon: mdi:solar-power
        state: >
          {% if has_value('sensor.abb_vsn300_ac_power') %}
            {{ states('sensor.abb_vsn300_ac_power') }}
          {% else %}
            {{ this.state }}
          {% endif %}
```

If you need to create a lot of those, maybe a compact form is better:

```yaml
template:
  - sensor:
      - name: ABB Inverter Power Stable
        device_class: power
        state_class: measurement
        unit_of_measurement: W
        icon: mdi:solar-power
        state: "{{ iif(has_value('sensor.abb_vsn300_ac_power'), states('sensor.abb_vsn300_ac_power'), this.state) }}"

```
