### DISCUSSION TITLE
v3.0.0 - New major release for HA 2023.9.x

### DISCUSSION THREAD

**Discussion by alexdelprete** [alexdelprete/ha-abb-powerone-pvi-sunspec#75] [Announcements]
This version was in the works since a couple of months, it isn't fully tested yet, but the problems introduced by HA 2023.9.x and pymodbus 3.5 forced me to push it sooner than I wanted to. This release seems to be working fine with HA 2023.9.x.

The code has mostly been refactored using DataUpdateCoordinator, etc. and many other things under the hood. It should perform better, I hope. :)

Enjoy and let me know in case of problems.

<hr /><em>This discussion was created from the release <a href='https://github.com/alexdelprete/ha-abb-powerone-pvi-sunspec/releases/tag/v3.0.0'>v3.0.0 - New major release for HA 2023.9.x</a>.</em>

**Comment by dexmorgan8888** [comment]
This update creates a new device which mirrors the existing one. Because of this, all entities under the one no longer function. The entity ids under the new device is now named with xxx_2  suffix, eg: solar_ac_current_2
This causes downstream sensors such to fail as helpers sensors with Riemann sum integral utility meter calculation.
Anyway to elegantly fix this? if not, I will be forced to revisit all my downstream sensors.
Thanks

**Reply by alexdelprete** [reply]
What version were you using previously? It shouldn't create a new device. The unique I'd is the inverter serial, so it should be the same.

**Comment by usrpend** [comment]
Same problem here. I was using v2.6.5. If I disable the old devices, this also rises one more issue: the old sensors stats are not showing in Energy panel anymore.

**Reply by alexdelprete** [reply]
You shouldn't have 2 devices because the unique_id remains the same.

can you please open `.storage/core.device_registry` file in the editor and look for `abb_powerone_pvi_sunspec`. Be careful not to modify anything...it's a critical HA file.

You should find only one instance, like this one:

```yaml
      {
        "area_id": null,
        "config_entries": [
          "54dcc9b0ac601ef0a7d78ebcd861cc76"
        ],
        "configuration_url": null,
        "connections": [],
        "disabled_by": "config_entry",
        "entry_type": null,
        "hw_version": null,
        "id": "935c4542399356b8c2b7293120faf791",
        "identifiers": [
          [
            "abb_powerone_pvi_sunspec",
            "077909-3G82-3112"
          ]
        ],
        "manufacturer": "Power-One",
        "model": "PVI-10.0-OUTD",
        "name_by_user": null,
        "name": "ABB VSN300",
        "sw_version": "C008",
        "via_device_id": null
      },
```

The identifiers are unique, because I used the s/n of the inverter, so a duplication isn't possible.

In `.storage/core.entity_registry` you can look for the sensors, and you will see that the unique_id starts with the s/n of the device, and that config_entry_id and device_id match the ones of the device (it's how sensor entities are associated to the device).

```yaml
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "54dcc9b0ac601ef0a7d78ebcd861cc76",
        "device_class": null,
        "device_id": "935c4542399356b8c2b7293120faf791",
        "disabled_by": "config_entry",
        "entity_category": null,
        "entity_id": "sensor.abb_vsn300_manufacturer",
        "hidden_by": null,
        "icon": null,
        "id": "24010e2479d6848bbcfb79b210e39760",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": null,
        "original_icon": "mdi:information-outline",
        "original_name": "Manufacturer",
        "platform": "abb_powerone_pvi_sunspec",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "077909-3G82-3112_comm_manufact",
        "unit_of_measurement": null
      },
```

Please let me know what you and @dexmorgan8888 find in those files.

Thanks.
